Feat: Added two routes for fetching team data
csivitu/hackstory pull request #9
Opened 2023-05-20 16:59 UTC by Realitylion

Deleted previous route for fetching team details which uses teamCode to get details.
Added two new routes: getTeamDetails (using user session) and listTeamNames (get all teams' names)

<Minor>
Eslint code changes have been made to delete.ts

2023-05-20 17:07 UTC, anandrajaram21 commented on src/pages/api/team/listTeamNames.ts
> +      return res.status(200).send(teamNames);
fix this to send an object containing an array of team names, instead of an object with the keys having the same names.

2023-05-20 17:08 UTC, anandrajaram21 requested changes
please make changes requested in comments

2023-05-20 17:26 UTC, Realitylion commented on src/pages/api/team/listTeamNames.ts
> +      return res.status(200).send(teamNames);
I have reviewed the changes and pushed them. Please check them.

2023-05-21 06:46 UTC, Realitylion commented
I have reviewed the changes and pushed them. Please check them.

2023-05-23 12:44 UTC, anandrajaram21 requested changes
can you make the following changes

2023-05-23 19:04 UTC, closed without merging